# Topics
- Economic (we use free software, should be affordable for diverse economic backgrounds)
- Ethical (we use free software and that's a good thing!)
- social impact/Educational: we want to design this for schools, so we need to respect tight hardware requirements and diverse export models (web browser, app, etc).
- Diversity and Inclusion/Accessibility (we want everyone to be able to play and understand)

# Essay
The primary goal of this project is to educate people about genetics through a videogame. Education is a difficult field, especially because of all of the different types of people that are its subject. This means that the audience of this project is especially broad. Video games are traditionally marketed to so called "gamers": people that play videogames for fun.  Gamers have certain expectations for games that allow them to pick up and play games quickly. The "WASD" keys are traditionally meant to move the player character, so most PC gamers will try these keys first when playing a new game.  A newcomer to the gaming scene would probably not assume that "WASD" are the movement keys, and without direction, would probably get frustrated trying to move their character around. This led the group to establish two central tenants of game design: intuitivity and accessibility.

 A broad audience of would-be students is going to contain people of many different backgrounds and the majority would probably not be composed of "gamers". One of the main constraints of game development then becomes appealing to this broad audience. To that end, we created a "mouse first" guideline for our team. This guideline specifies that all player interactions, with some exceptions, is to be performed with the pointing device. This avoids alienating players who do not have a gaming background by taking advantage of an input device they should be familiar with: the mouse. Additionally, the game should not be mechanically difficult, i.e., trained hand-eye coordination should not be a requirement to be "good" at the game. Essentially, our main philosophy for game design is: **the game should be designed to *teach concepts*, anything that gets in the way of that should be scrapped.** That being said, appealing to every possible individual is an exercise in futility, so we constrained our audience to be high school aged children. This allows us to match a particular curriculum (common core) while also assuming some basic skills (reading, basic computer skills).

Along the same lines, language barriers and disability should not prevent someone from playing the game. To that end, international language support is included in our design. This entails some extra work, but luckily, tools are built into our chosen game engine that simplify this process. Integral use of color and sound will be avoided to ensure that colorblindness and deafness are not a barrier to the player. The use of the "mouse first" design guideline also aids in allowing those with mechanical disabilities to play relatively unhindered as well. 

Economic accessibility is important also. The game should be affordable, easily acquired and playable on a wide variety of devices. To make this more feasible, the group decided that use of free software would not only lower the cost of development, but would also make it easier to make the game affordable. All software used in development is open source and free, except for the music software, as no suitable alternative exists. The game engine in particular is completely free, as opposed to most game engines, which take some of the profit for their own. Using a free game engine allows us to dramatically lower the price of the final product, assuming we work somewhat professionally to maintain the game.

Ethically, use of free software is also important. It facilitates a community of developers through mutual contribution and forms a neutral base for companies to base their products on. In the worst-case scenario, there is also a functional improvement to working with free software: forking. If the game engine, for example, were to cease to be maintained, we ourselves could maintain it for our purposes. The licence for our game is informed by this philosophy of "giving back" to the community. The license is essentially an "open source, closed distribution" license. This way, those that wish to contribute can freely download and play our game, but cannot distribute it, allowing us to make the profit needed for continued financial support.

Education, accessibility and maintainability are the main concerns needed to achieve the goal of the project: educating people about genetics. An interface designed for a diverse audiences allows us to create a product aimed at an extremely large group of people, while the use of free open source software makes it possible for that audience to actually acquire and use that product in the long term. 
